name: Myna
options:
  bundleIdPrefix: com.and1truong
  xcodeVersion: "16.0"
targets:
  Myna:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Myna
    info:
      path: Myna/Info.plist
      properties:
        CFBundleDisplayName: Myna
        UILaunchScreen_Generation: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSupportsIndirectInputEvents: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.and1truong.myna
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "0.1"
        TARGETED_DEVICE_FAMILY: "1,2"
  MynaTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: MynaTests
    dependencies:
      - target: Myna
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.and1truong.myna.tests
        SWIFT_VERSION: "5.0"
